name: Build

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        id: install_deps
        run: npm install
        env:
          CI: true

      - name: Test for Server (Unit)
        run: npm run test --workspace=server -- --ci --reporters=default --reporters=jest-junit
        env:
          JEST_JUNIT_OUTPUT_NAME: 'junit-unit.xml'
        continue-on-error: true

      - name: Test for Server (E2E)
        run: npm run test:e2e --workspace=server -- --ci --reporters=default --reporters=jest-junit
        env:
          JEST_JUNIT_OUTPUT_NAME: 'junit-e2e.xml'
        continue-on-error: true

      - name: Test for Client
        run: |
          npm run build-api-client
          npm run test --workspace=client -- --browsers=ChromeHeadless --reporters=progress,junit --watch=false
        continue-on-error: true

      - name: Upload test report for Server (Unit)
        uses: mikepenz/action-junit-report@eb1a2b2dbd4c45341235503b2c3edfa46d2ec3de
        if: always()
        with:
          check_name: 'Test Report - Server (Unit)'
          report_paths: 'server/junit-unit.xml'
          fail_on_failure: True
          require_tests: True

      - name: Upload test report for Server (E2E)
        uses: mikepenz/action-junit-report@eb1a2b2dbd4c45341235503b2c3edfa46d2ec3de
        if: always()
        with:
          check_name: 'Test Report - Server (E2E)'
          report_paths: 'server/junit-e2e.xml'
          fail_on_failure: True
          require_tests: True

      - name: Upload test report for Client
        uses: mikepenz/action-junit-report@eb1a2b2dbd4c45341235503b2c3edfa46d2ec3de
        if: always()
        with:
          check_name: 'Test Report - Client'
          report_paths: 'client/TESTS-*.xml'
          fail_on_failure: True
          require_tests: True
