name: Build

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install
        env:
          CI: true

      - name: Test app
        run: npm run test:ci

      - name: Upload test report for client
        uses: mikepenz/action-junit-report@41a3188dde10229782fd78cd72fc574884dd7686
        if: always()
        with:
          check_name: 'Test Report - Client'
          report_paths: 'client/TESTS-*.xml'
          fail_on_failure: True
          require_tests: True

      - name: Upload test report for server
        uses: mikepenz/action-junit-report@41a3188dde10229782fd78cd72fc574884dd7686
        if: always()
        with:
          check_name: 'Test Report - Server'
          report_paths: 'server/junit.xml'
          fail_on_failure: True
          require_tests: True
